const actionTypes = {
    FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
    FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILURE: 'FETCH_ALL_PRODUCTS_FAILURE',

    ADD_PRODUCTS: 'ADD_PRODUCTS',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCTS_FAILURE: 'ADD_PRODUCTS_FAILURE',

    UPLOAD_IMAGE: 'UPLOAD_IMAGE',
    UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
    UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',



    NEWIN_PRODUCTS: 'NEWIN_PRODUCTS',
    NEWIN_PRODUCT_SUCCESS: 'NEWIN_PRODUCT_SUCCESS',
    NEWIN_PRODUCTS_FAILURE: 'NEWIN_PRODUCTS_FAILURE',


    GET_PRODUCT: 'GET_PRODUCT',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',

    UPDATE_ONE: 'UPDATE_ONE',
    UPDATE_ONE_SUCCESS: 'UPDATE_ONE_SUCCESS',
    UPDATE_ONE_FAILURE: 'UPDATE_ONE_FAILURE',

    GET_PRODUCT_IMAGES: 'GET_PRODUCT_IMAGES',
    GET_PRODUCT_IMAGES_SUCCESS: 'GET_PRODUCT_IMAGES_SUCCESS',
    GET_PRODUCT_IMAGES_FAILURE: 'GET_PRODUCT_IMAGES_FAILURE',

    GET_PRODUCT_BY_CATEGORY: 'GET_PRODUCT_BY_CATEGORY',
    GET_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_SUCCESS',
    GET_PRODUCT_BY_CATEGORY_FAILURE: 'GET_PRODUCT_BY_CATEGORY_FAILURE',
   

};

export default actionTypes;